folio = Field("folio")
telefono = Field("telefono")
tipo_servicio = Field("tipo_servicio")
sector = Field("sector")
cable = Field("cable")
par = Field("par")
red = Field("red")
fecha_reporte = Field("fecha_reporte","datetime")
clave = Field("clave")
grupo = Field("grupo")
demora = Field("demora","double")
fecha_cierre = Field("fecha_cierre","datetime")
despachador = Field("despachador")
demora_en_hrs = Field("demora_en_hrs","double")
central_tel = Field("central_tel")
centro_tel = Field("centro_tel","reference ctlc",requires=IS_IN_DB(db,"ctlc.id","%(nombre)s"))
gerencia = Field("gerencia")
terminal = Field("terminal")
direccion = Field("direccion")
db.define_table("siprec_reparadas_rd",folio,telefono,tipo_servicio,sector,cable,par,red,fecha_reporte,clave,grupo,demora,fecha_cierre,despachador,demora_en_hrs,central_tel,centro_tel,gerencia,terminal,direccion,migrate=0)
#db.interrupciones_siprec.truncate('RESTART IDENTITY CASCADE')

servicio = Field("servicio")
demora_total = Field("demora_total","double")
problema = Field("problema")
db.define_table("siprec_pendientes_inicio_rd",servicio,tipo_servicio,sector,cable,par,fecha_reporte,grupo,demora,folio,demora_total,central_tel,centro_tel,gerencia,terminal,\
                direccion,problema,red,migrate=0)

servicio = Field("servicio")
demora_total = Field("demora_total","double")
problema = Field("problema")
db.define_table("siprec_pendientes_cierre_rd",servicio,tipo_servicio,sector,cable,par,fecha_reporte,grupo,demora,folio,demora_total,central_tel,centro_tel,gerencia,terminal,\
                direccion,problema,red,migrate=0)

tipo_servicio = Field("tipo_servicio")
db.define_table("servicios_rd",tipo_servicio,migrate=1)
